version: '3.8'
services:
  postgres_user:
    container_name: postgres_user
    image: postgres:alpine
    ports:
      - "1400:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_dev
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-user-data:/var/lib/postgresql/data
    networks:
      - sb_network
    command: -p 1400
  postgres_supplier:
    container_name: postgres_supplier
    image: postgres:alpine
    ports:
      - "1401:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_dev
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-supplier-data:/var/lib/postgresql/data
    networks:
      - sb_network
    command: -p 1401
  postgres_item:
    container_name: postgres_item
    image: postgres:alpine
    ports:
      - "1402:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_dev
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-item-data:/var/lib/postgresql/data
    networks:
      - sb_network
    command: -p 1402
  sb_server:
    container_name: sb_server
    build:
      context: ./sb-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - EUREKA_DEFAULT_ZONE=http://localhost:8000/eureka
    networks:
      - sb_network
    command: -p 8000
  sb_user:
    container_name: sb_user
    build:
      context: ./sb-user
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres_user:1400/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_dev
      - EUREKA_DEFAULT_ZONE=http://sb_server:8000/eureka
      - EUREKA_INSTANCE_HOST=sb_server
    depends_on:
      - postgres_user
    networks:
      - sb_network
    command: -p 8001
  sb_supplier:
    container_name: sb_supplier
    build:
      context: ./sb-supplier
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres_supplier:1401/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_dev
      - EUREKA_DEFAULT_ZONE=http://sb_server:8000/eureka
      - EUREKA_INSTANCE_HOST=sb_server
    depends_on:
      - postgres_supplier
    networks:
      - sb_network
    command: -p 8002
  sb_item:
    container_name: sb_item
    build:
      context: ./sb-item
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres_item:1402/postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_dev
      - EUREKA_DEFAULT_ZONE=http://sb_server:8000/eureka
      - EUREKA_INSTANCE_HOST=sb_server
    depends_on:
      - postgres_item
    networks:
      - sb_network
    command: -p 8003
networks:
  sb_network:
    driver: bridge
